name: DiscordSRV
version: ${project.version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz
website: https://github.com/Scarsz/DiscordSRV

main: com.scarsz.discordsrv.platforms.BukkitPlatform
database: false
softdepend: [HeroChat, Legendchat, LunaChat, Multiverse-Core, TownyChat, Vault, VentureChat]
#load: STARTUP

commands:
  discord:
    description: DiscordSRV commands
    usage: /discord

permissions:
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true
  discordsrv.silentjoin:
    description: whether or not to have join messages for players with this permission to be silenced
    default: false
  discordsrv.silentquit:
    description: whether or not to have quit messages for players with this permission to be silenced
    default: false